version : '3.7'
services:
    mysqldb:
        image: mysql:8.4.0
        restart: always
        ports:
        - "3306:3306"
        environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        volumes:
        - mysql-parser-data:/var/lib/mysql
        networks:
        - springboot-mysql-network


    frontend:
        build:
          context: ./visualizer
          dockerfile : Dockerfile
        ports:
        - "4200:4200"
        depends_on:
          backend:
            condition: service_started
            restart: true


    backend:
        build:
           context: ./backend
           dockerfile : Dockerfile
        ports:	
        - "8080:8080"
        depends_on:
          mysqldb:
            condition: service_started
            restart: true
        volumes:
          - ${CSV_FOLDER_PATH}:/csvfolder
        environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
        - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
        networks:
        - springboot-mysql-network
   
networks:
   springboot-mysql-network:
      name: springboot-mysql-network
volumes:
    mysql-parser-data:



